from pydantic import BaseModel


class Features(BaseModel):
    """Represents the feature set for a health-related prediction model."""

    highbp: float
    highchol: float
    cholcheck: float
    bmi: float
    smoker: float
    stroke: float
    heartdiseaseorattack: float
    physactivity: float
    fruits: float
    veggies: float
    hvyalcoholconsump: float
    anyhealthcare: float
    nodocbccost: float
    genhlth: float
    menthlth: float
    physhlth: float
    diffwalk: float
    sex: float
    age: float
    education: float
    income: float


class Data(BaseModel):
    """
    Represents a dataset of features for multiple records.

    Attributes:
        data (dict[int, Features]): A dictionary mapping record IDs to their corresponding features.
    """

    data: dict[int, Features]


class Predictions(BaseModel):
    """
    Represents the predictions generated by the model.

    Attributes:
        predictions (dict[int, int]): A dictionary mapping record IDs to their predicted class labels.
    """

    predictions: dict[int, int]
